- modality: text
  name: text
  processor: text_processing
- modality: image
  name: image
  processor: image_processing
- modality: audio
  name: audio
  processor: audio_processing
- modality: video
  name: video
  processor: video_processing
